[env:wiscore_rak4631]
extends=nrf52840_base
board = wiscore_rak4631
build_src_filter = 
  ${nrf52840_base.build_src_filter} 
  +<../variants/NRF52/wiscore_rak4631>
build_flags =
    ${nrf52840_base.build_flags}
    -I variants/NRF52/wiscore_rak4631
lib_deps = 
  ${nrf52840_base.lib_deps}




