; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
name = meshScale
default_envs = heltec_T114_v2, heltec_wifi_lora_32_V3, rak4630

extra_configs = 
	; Variant base configs
	variants/Variant_base/*.ini
	; Core variants
    variants/Core/*/*/platformio.ini
	; Community variants
    variants/Community/*/*/platformio.ini
    
[env]
build_flags = 
	-std=c++11
	;-Wall
	;-Wextra
	-Wno-missing-field-initializers
	-Wno-format
	-Wno-unused-parameter
	-Wno-unknown-pragmas
	;-Isrc
	;-DLIBRARY_TEST
	;-DNDEBUG
	-DRNS_USE_FS
	-DRNS_PERSIST_PATHS
lib_deps=
	nanopb/Nanopb@0.4.91
extra_scripts= pre:./utils/extra_script.py


[arduino_base]
framework = arduino
extends= env
monitor_speed = 115200
build_src_filter = 
    ${env.build_src_filter}
build_flags= 
    ${env.build_flags}
lib_deps=
    ${env.lib_deps}



[reticulum_base]
build_flags=
    -fexceptions
build_unflags=
    -fno-exceptions
lib_deps=
    https://github.com/attermann/microReticulum.git#d538ca2be225166c8af0da9ac9641bdaa1f2dded
	https://github.com/attermann/microStore.git#ceea8f585c8b22ad238fb290961b8311cb83c516

[radiolib_base]
lib_deps=
    jgromes/RadioLib@^7.4.0

