[env:heltec_T114_v2]
extends = nrf52840_base
board = heltec_T114_v2
build_src_filter = 
    ${nrf52840_base.build_src_filter} 
    +<../variants/Core/NRF52/heltec_T114_v2>
build_flags =
    ${nrf52840_base.build_flags}
    -I variants/Core/NRF52/heltec_T114_v2
    -D BOARD_heltec_T114_v2
    -D EXCLUDE_INTERFACE_UDP
    