[env:heltec_wifi_lora_32_V3]
extends=esp32s3_base
board = heltec_wifi_lora_32_V3
build_src_filter = 
    ${esp32s3_base.build_src_filter} 
    +<../variants/Core/ESP32/heltec_wifi_lora_32_V3>
build_flags =
    ${esp32s3_base.build_flags}
    -I variants/Core/ESP32/heltec_wifi_lora_32_V3
