[env:heltec_T114_v2]
extends = nrf52840_base
board = heltec_T114_v2
build_src_filter = ${nrf52840_base.build_src_filter} +<../variants/NRF52/heltec_T114_v2>
build_flags =
    ${nrf52840_base.build_flags}
    -I variants/NRF52/heltec_T114_v2
lib_deps = 
    ${nrf52840_base.lib_deps}