[env:heltec_wifi_lora_32_V3]
extends=esp32s3_base
board = heltec_wifi_lora_32_V3
build_flags =
    ${esp32s3_base.build_flags}
    -I variants/ESP32/heltec_wifi_lora_32_V3

lib_deps=
    ${esp32s3_base.lib_deps} 
