[env:rak4630]
extends=nrf52840_base
board = rak4630
build_src_filter = 
  ${nrf52840_base.build_src_filter} 
  +<../variants/Core/NRF52/rak4630>
build_flags =
    ${nrf52840_base.build_flags}
    -I variants/Core/NRF52/rak4630
lib_deps = 
  ${nrf52840_base.lib_deps}




